### ISSUE TITLE
Mainframe

### ISSUE THREAD

**Issue by v1gnesh** [IBM/drawIT#1]
Hi,

Is there any chance at all of adding support for mainframe assets (shapes, icons, etc.).
Would be nice to use this to represent a site's mainframe landscape (h/w & s/w) with official assets.

**Comment by jaywarfield** [comment]
Hi,
Mainframe assets should definitely be considered.  Since this is for additional features to IBM2 diagrams, particularly icons, and if you are internal to IBM please ping me for the channels to make this request. 
Thanks for your interest!

**Comment by v1gnesh** [comment]
I'm not an IBMer... which means I won't really know if this will happen?

**Comment by jaywarfield** [comment]
Hi,
In that case let's keep this open until we review further.  Are you referring to only on-premise mainframe hardware/software or also cloud-related?  
Thanks!

**Comment by v1gnesh** [comment]
Thank you, mainly referring to on-prem.
I noticed that some mainframe & IBM Cloud app icons are here - https://carbondesignsystem.com/guidelines/icons/library/, under App Catalogue.

**Comment by jaywarfield** [comment]
Hi, there is a new external link planned soon for architecture icons if all goes well that would be best for this request, and I also added your request internally, we have had to iron out problems in general.  Thanks!
