### ISSUE TITLE
What does ~/Documents/drawIT/vpc-web.json look like?

### ISSUE THREAD

**Issue by shenghu** [IBM/drawIT#2]
@jaywarfield in `rungui.sh`, it uses `~/Documents/drawIT/vpc-web.json`. But I don't find any json `examples`. Can you please provide an example or explain how to generate it?

**Comment by jaywarfield** [comment]
Hi, I missed this issue, this project has just been moved to InnerSource, let me know if you have any question via internal mail.  Thanks!
